// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolarLedger.Infrastructure.Persistence;

#nullable disable

namespace SolarLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SolarLedgerDbContext))]
    [Migration("20260925063133_AddSettlementRuns")]
    partial class AddSettlementRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SOLAR")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarLedger.Domain.Communities.Community", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("DistributionPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("IncentiveTariffEurPerMwh")
                        .HasColumnType("NUMBER(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PrimarySubstationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("PrimarySubstationCode");

                    b.ToTable("COMMUNITIES", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Members.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommunityId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("MEMBERS", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Metering.EnergyReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Hour")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("InjectedKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.Property<long>("PodId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("WithdrawnKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("PodId", "Hour")
                        .IsUnique();

                    b.ToTable("ENERGY_READINGS", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Pods.Pod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MemberId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("PodCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("PodCode")
                        .IsUnique();

                    b.ToTable("PODS", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.HourlyShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Hour")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("InjectedKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.Property<long>("SettlementRunId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("SharedKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.Property<decimal>("WithdrawnKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementRunId", "Hour")
                        .IsUnique();

                    b.ToTable("HOURLY_SHARES", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.MemberSettlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AttributedKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)");

                    b.Property<decimal>("IncentiveEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<long>("MemberId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("SettlementRunId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementRunId", "MemberId")
                        .IsUnique();

                    b.ToTable("MEMBER_SETTLEMENTS", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.SettlementRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLAIMED_AT_UTC");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CLAIMED_BY");

                    b.Property<long>("CommunityId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("COMMUNITY_ID");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COMPLETED_ON_UTC");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_ON_UTC");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PERIOD_END_UTC");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PERIOD_START_UTC");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("POLICY_NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalIncentiveEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("TOTAL_INCENTIVE_EUR");

                    b.Property<decimal>("TotalSharedKwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("DECIMAL(18,3)")
                        .HasColumnName("TOTAL_SHARED_KWH");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("CommunityId", "PeriodStartUtc", "PeriodEndUtc")
                        .IsUnique();

                    b.ToTable("SETTLEMENT_RUNS", "SOLAR");
                });

            modelBuilder.Entity("SolarLedger.Domain.Members.Member", b =>
                {
                    b.HasOne("SolarLedger.Domain.Communities.Community", "Community")
                        .WithMany("Members")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SolarLedger.Domain.Metering.EnergyReading", b =>
                {
                    b.HasOne("SolarLedger.Domain.Pods.Pod", "Pod")
                        .WithMany("Readings")
                        .HasForeignKey("PodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pod");
                });

            modelBuilder.Entity("SolarLedger.Domain.Pods.Pod", b =>
                {
                    b.HasOne("SolarLedger.Domain.Members.Member", "Member")
                        .WithMany("Pods")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.HourlyShare", b =>
                {
                    b.HasOne("SolarLedger.Domain.Settlement.SettlementRun", "SettlementRun")
                        .WithMany("HourlyShares")
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementRun");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.MemberSettlement", b =>
                {
                    b.HasOne("SolarLedger.Domain.Settlement.SettlementRun", "SettlementRun")
                        .WithMany("MemberSettlements")
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementRun");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.SettlementRun", b =>
                {
                    b.HasOne("SolarLedger.Domain.Communities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SolarLedger.Domain.Communities.Community", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SolarLedger.Domain.Members.Member", b =>
                {
                    b.Navigation("Pods");
                });

            modelBuilder.Entity("SolarLedger.Domain.Pods.Pod", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("SolarLedger.Domain.Settlement.SettlementRun", b =>
                {
                    b.Navigation("HourlyShares");

                    b.Navigation("MemberSettlements");
                });
#pragma warning restore 612, 618
        }
    }
}
